AVPacket Fix
SunshineStream/Sunshine pull request #125
Opened 2022-04-10 05:46 UTC by comwizz2

## Description

This PR changes the codebase to wrap AVPacket instead of extending it.

According to ffmpeg's documentation: 

"sizeof(AVPacket) being a part of the public ABI is deprecated. once av_init_packet() is removed, new packets will only be able to be allocated with [av_packet_alloc()](https://ffmpeg.org/doxygen/trunk/group__lavc__packet.html#gaaf85aa950695631e0217a16062289b66), and new fields may be added to the end of the struct with a minor bump."

I believe this to mean extending AVPacket is fragile and prone to break if things are changed in ffmpeg

In this case, the extended struct did not clear the memory for AVPacket.opaque_ref, so it was not guaranteed to be correctly set to nullptr.
That meant that when encode was called it would try to free a random pointer (since opaque_ref is a AVBuffer) and segfault.
While the issue in question could have been solved by setting that field to nullptr in the constructor, I though changing the codebase to use AVPacket the proper way was the correct move here instead to increase the resiliency of this code.

I have tested this with nvapi encoder with no issues in video (I am having a separate audio issue I plan on looking at) but do not have any other encoders setup to test. (Software encoding is giving me a separate problem, already documented as an issue.)

Note that my C++ is rough, but I believe this should still keep all the correct memory ref/ownership to prevent leaks (and I did not see an increase in memory usage after letting a video steam for some time.)

### Issues Fixed or Closed

- Fixes #(124)

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated the documentation blocks for new or existing components

2022-04-10 16:43 UTC, comwizz2 commented
I redid the PR to fix an extraneous debugging include (iostream) and to properly apply clang-format!

2022-04-11 19:13 UTC, TheElixZammuto commented
Working as intended on libx264 and AMF on Windows, but I would wait for some NVEnc feedback before merging

2022-04-11 19:13 UTC, TheElixZammuto requested changes
I would wait some feedback from NVEnc before merging this

2022-04-12 21:13 UTC, Logical-sh commented
Rebased to fix the merge conflict with the new try catch blocks.

2022-04-29 14:43 UTC, KuleRucket commented
I have tested this PR using nvenc (with nvfbc) and it is working fine for me. I don't see any difference in the logs and behaviour compared to the nightly branch.

2022-04-29 14:45 UTC, merged